#!/bin/bash

curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
sudo rm -rf /opt/nvim
sudo tar -C /opt -xzf nvim-linux64.tar.gz

sudo apt update
sudo apt install -y zsh
chsh -s $(which zsh)

sudo apt install -y gcc
sudo apt install -y build-essential
sudo apt install -y stow

sudo apt update
sudo apt install software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install ansible

ansible-playbook --connection=local 127.0.0.1 playbook.yml
